package common

// Status codes for the binary API
const (
	STATUS0_SUCCESS              = 0
	STATUS1_PROCESSING_ERROR     = 1
	STATUS2_MISSING_DEVICE_TOKEN = 2
	STATUS3_MISSING_TOPIC        = 3
	STATUS4_MISSING_PAYLOAD      = 4
	STATUS5_INVALID_TOKEN_SIZE   = 5
	STATUS6_INVALID_TOPIC_SIZE   = 6
	STATUS7_INVALID_PAYLOAD_SIZE = 7
	STATUS8_UNSUBSCRIBE          = 8
)
