# Uniqush Copyright (c) 2011 Nan Deng
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

include $(GOROOT)/src/Make.inc

TARG=uniqush
GOFILES=\
	notification.go\
	pusher.go\
	deliverypoint.go\
	pushserviceprovider.go\
	servicetype.go\
	ostype.go\
	c2dmpusher.go\

include $(GOROOT)/src/Make.pkg
