include $(GOROOT)/src/Make.inc

TARG=uniqush
GOFILES=\
	notification.go\
	pusher.go\
	deliverypoint.go\
	pushserviceprovider.go\
	servicetype.go\
	ostype.go\
	c2dmpusher.go\
	request.go\
	frontend.go\
	webfrontend.go\
	backend.go\
	eventwriter.go\
	reqprocessors.go\
	kvcache.go\
	kvcachestrategy.go\
	kvstorage.go\
	dbconfig.go\
	uniqushdb.go\
	uniqushredisdb.go\
	dbfrontdesk.go\
	pushprocessor.go\
	taskqueue.go\
	log.go\


include $(GOROOT)/src/Make.pkg
