include $(GOROOT)/src/Make.inc

TARG=github.com/monnand/uniqush/uniqush
GOFILES=\
	notification.go\
	deliverypoint.go\
	pushserviceprovider.go\
	request.go\
	frontend.go\
	webfrontend.go\
	backend.go\
	eventwriter.go\
	reqprocessors.go\
	kvcache.go\
	kvcachestrategy.go\
	kvstorage.go\
	dbconfig.go\
	uniqushdb.go\
	uniqushredisdb.go\
	dbfrontdesk.go\
	pushprocessor.go\
	log.go\
	uniqushsys.go\
	pushservicemngr.go\
	pushservicetype.go\
	pushpeer.go\
	objmempool.go\
	c2dm.go\
	apns.go\

include $(GOROOT)/src/Make.pkg
